name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use a GitHub runner for CI

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Set the Python version you're using

    - name: Deploy to server
      env:
        DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      run: |
        # Ensure the server's host key is added to known_hosts
        mkdir -p ~/.ssh
        ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
        
        # Create a temporary file for the private key
        echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # SSH into the server and pull the latest code from GitHub
        ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_SERVER << 'EOF'
          cd /home/averyg99/web/Medi-care-Backend
          git pull origin main  # Pull latest code

          # Activate the existing virtual environment
          source /home/averyg99/web/Medi-care-Backend/env/bin/activate

          # Install dependencies on the server
          pip install -r requirements.txt

          # Restart the app service (Flask)
          systemctl restart flask-server  # Restart your app service
        EOF
